#!/bin/bash

# Fix Migration Permissions Script
# Run this on your production server to fix permission issues with Django migrations

set -e

echo "🔧 Fixing migration permissions and creating missing migration..."

# Detect production path structure
if [ -d "/var/www/python/invpro" ]; then
    PROD_PATH="/var/www/python/invpro"
    BACKEND_PATH="$PROD_PATH/apps/backend"
    MIGRATIONS_PATH="$BACKEND_PATH/shopify_integration/migrations"
elif [ -d "/var/www/invpro/apps/backend" ]; then
    PROD_PATH="/var/www/invpro"
    BACKEND_PATH="$PROD_PATH/apps/backend"
    MIGRATIONS_PATH="$BACKEND_PATH/shopify_integration/migrations"
else
    echo "❌ Could not find production directory. Please set PROD_PATH manually."
    exit 1
fi

cd "$BACKEND_PATH"

# Find Django user
DJANGO_USER=$(ps aux | grep -E "python.*manage.py|gunicorn|uwsgi" | grep -v grep | head -1 | awk '{print $1}')
if [ -z "$DJANGO_USER" ]; then
    # Try to get from systemd service
    DJANGO_USER=$(systemctl show -p User invpro 2>/dev/null | cut -d= -f2 || echo "www-data")
fi

echo "📋 Detected Django user: $DJANGO_USER"
echo "📁 Migrations path: $MIGRATIONS_PATH"

# Step 1: Fix permissions
echo ""
echo "🔐 Step 1: Fixing permissions..."

# Check current ownership
CURRENT_OWNER=$(stat -c '%U:%G' "$MIGRATIONS_PATH" 2>/dev/null || echo "unknown")
echo "   Current owner: $CURRENT_OWNER"

# Fix ownership
if [ "$DJANGO_USER" != "root" ]; then
    echo "   Setting ownership to $DJANGO_USER..."
    sudo chown -R "$DJANGO_USER:$DJANGO_USER" "$MIGRATIONS_PATH" 2>/dev/null || {
        echo "   ⚠️  Could not change ownership. You may need to run:"
        echo "   sudo chown -R $DJANGO_USER:$DJANGO_USER $MIGRATIONS_PATH"
    }
fi

# Fix permissions
echo "   Setting permissions to 775..."
sudo chmod -R 775 "$MIGRATIONS_PATH" 2>/dev/null || {
    echo "   ⚠️  Could not change permissions. You may need to run:"
    echo "   sudo chmod -R 775 $MIGRATIONS_PATH"
}

# Step 2: Check existing migrations
echo ""
echo "📊 Step 2: Checking existing migrations..."

if [ -f "$MIGRATIONS_PATH/0003_add_error_count.py" ]; then
    echo "   ✅ Found 0003_add_error_count.py"
    NEXT_MIGRATION="0004_alter_shopifyintegration_api_version.py"
else
    echo "   ⚠️  0003_add_error_count.py not found"
    NEXT_MIGRATION="0003_alter_shopifyintegration_api_version.py"
fi

# Step 3: Create missing migration if needed
echo ""
echo "📝 Step 3: Checking for migration file..."

if [ ! -f "$MIGRATIONS_PATH/$NEXT_MIGRATION" ]; then
    echo "   Creating $NEXT_MIGRATION..."
    
    # Determine dependency
    if [ "$NEXT_MIGRATION" = "0004_alter_shopifyintegration_api_version.py" ]; then
        DEPENDENCY="('shopify_integration', '0003_add_error_count')"
    else
        DEPENDENCY="('shopify_integration', '0002_initial')"
    fi
    
    cat > "/tmp/$NEXT_MIGRATION" << 'EOF'
# Generated by Django 5.1.1 on 2025-01-27

from django.db import migrations, models


def get_default_api_version():
    """Get default API version from environment or use default."""
    import os
    return os.getenv("SHOPIFY_API_VERSION", "2024-10")


class Migration(migrations.Migration):

    dependencies = [
        DEPENDENCY_PLACEHOLDER,
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyintegration',
            name='api_version',
            field=models.CharField(
                default=get_default_api_version,
                help_text='Shopify API version used for requests',
                max_length=20
            ),
        ),
    ]
EOF
    
    # Replace placeholder
    sed -i "s/DEPENDENCY_PLACEHOLDER/$DEPENDENCY/" "/tmp/$NEXT_MIGRATION"
    
    # Copy to migrations directory
    sudo cp "/tmp/$NEXT_MIGRATION" "$MIGRATIONS_PATH/$NEXT_MIGRATION"
    sudo chown "$DJANGO_USER:$DJANGO_USER" "$MIGRATIONS_PATH/$NEXT_MIGRATION"
    sudo chmod 644 "$MIGRATIONS_PATH/$NEXT_MIGRATION"
    
    echo "   ✅ Created $NEXT_MIGRATION"
    rm -f "/tmp/$NEXT_MIGRATION"
else
    echo "   ✅ Migration file already exists: $NEXT_MIGRATION"
fi

# Step 4: Verify migrations
echo ""
echo "✅ Step 4: Verifying migrations..."

if [ -f "$BACKEND_PATH/venv/bin/activate" ]; then
    source "$BACKEND_PATH/venv/bin/activate"
    echo "   Checking migration status..."
    python manage.py showmigrations shopify_integration || echo "   ⚠️  Could not check migrations (this is okay if Django isn't fully configured)"
else
    echo "   ⚠️  Virtual environment not found at $BACKEND_PATH/venv"
fi

# Step 5: Summary
echo ""
echo "✅ Permissions fix complete!"
echo ""
echo "📋 Next steps:"
echo "   1. Verify permissions:"
echo "      ls -la $MIGRATIONS_PATH"
echo ""
echo "   2. Run migrations:"
echo "      cd $BACKEND_PATH"
echo "      source venv/bin/activate"
echo "      python manage.py migrate"
echo ""
echo "   3. Verify all migrations applied:"
echo "      python manage.py showmigrations shopify_integration"

