# Generated by Django 5.1.1 on 2025-11-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant ID for multi-tenant isolation')),
                ('po_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('processing', 'Processing'), ('in-transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='draft', max_length=40)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant ID for multi-tenant isolation')),
                ('request_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=40)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant ID for multi-tenant isolation')),
                ('supplier_code', models.CharField(blank=True, db_index=True, max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('contact_person', models.CharField(blank=True, help_text='Primary contact person name', max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0, help_text='Supplier rating out of 5.0', max_digits=3)),
            ],
        ),
    ]
