# Generated by Django 5.1.1 on 2025-11-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant ID for multi-tenant isolation')),
                ('entity_type', models.CharField(choices=[('product', 'Product'), ('order', 'Sales Order'), ('purchase_order', 'Purchase Order'), ('purchase_request', 'Purchase Request'), ('warehouse', 'Warehouse'), ('transfer', 'Transfer'), ('supplier', 'Supplier'), ('customer', 'Customer')], max_length=50)),
                ('prefix', models.CharField(default='DOC', max_length=20)),
                ('include_year', models.BooleanField(default=False)),
                ('include_month', models.BooleanField(default=False)),
                ('separator', models.CharField(default='-', max_length=5)),
                ('padding', models.IntegerField(default=3)),
                ('current_sequence', models.IntegerField(default=0)),
                ('reset_on_year', models.BooleanField(default=False)),
                ('reset_on_month', models.BooleanField(default=False)),
                ('last_reset_year', models.IntegerField(blank=True, null=True)),
                ('last_reset_month', models.IntegerField(blank=True, null=True)),
                ('sample_format', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Number Sequence',
                'verbose_name_plural': 'Number Sequences',
            },
        ),
    ]
