# Generated by Django 5.1.1 on 2025-11-08 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopify_integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifycustomer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopify_integration_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopifycustomer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopify_integration_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopifyintegration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopify_integration_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopifyintegration',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopify_integration_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopifycustomer',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='shopify_integration.shopifyintegration'),
        ),
        migrations.AddField(
            model_name='shopifyinventorylevel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopify_integration_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopifyinventorylevel',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_levels', to='shopify_integration.shopifyintegration'),
        ),
        migrations.AddField(
            model_name='shopifyinventorylevel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopify_integration_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopify_integration_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shopify_integration.shopifyintegration'),
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopify_integration_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopifyproduct',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopify_integration_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopifyproduct',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shopify_integration.shopifyintegration'),
        ),
        migrations.AddField(
            model_name='shopifyproduct',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopify_integration_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopifysynclog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopify_integration_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopifysynclog',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='shopify_integration.shopifyintegration'),
        ),
        migrations.AddField(
            model_name='shopifysynclog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopify_integration_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='shopifyintegration',
            index=models.Index(fields=['tenant_id', 'status'], name='shopify_int_tenant__032682_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shopifyintegration',
            unique_together={('tenant_id', 'store_url')},
        ),
        migrations.AddIndex(
            model_name='shopifycustomer',
            index=models.Index(fields=['integration', 'shopify_customer_id'], name='shopify_int_integra_c4d376_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifycustomer',
            index=models.Index(fields=['tenant_id', 'email'], name='shopify_int_tenant__11e46b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shopifycustomer',
            unique_together={('integration', 'shopify_customer_id')},
        ),
        migrations.AddIndex(
            model_name='shopifyinventorylevel',
            index=models.Index(fields=['integration', 'shopify_inventory_item_id'], name='shopify_int_integra_adbca9_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifyinventorylevel',
            index=models.Index(fields=['tenant_id', 'sku'], name='shopify_int_tenant__7f616d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shopifyinventorylevel',
            unique_together={('integration', 'shopify_inventory_item_id', 'shopify_location_id')},
        ),
        migrations.AddIndex(
            model_name='shopifyorder',
            index=models.Index(fields=['integration', 'shopify_order_id'], name='shopify_int_integra_cdced4_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifyorder',
            index=models.Index(fields=['tenant_id', 'processed_at'], name='shopify_int_tenant__4b4b05_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shopifyorder',
            unique_together={('integration', 'shopify_order_id')},
        ),
        migrations.AddIndex(
            model_name='shopifyproduct',
            index=models.Index(fields=['integration', 'shopify_product_id'], name='shopify_int_integra_f17d80_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifyproduct',
            index=models.Index(fields=['tenant_id', 'title'], name='shopify_int_tenant__f4fd17_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shopifyproduct',
            unique_together={('integration', 'shopify_product_id')},
        ),
        migrations.AddIndex(
            model_name='shopifysynclog',
            index=models.Index(fields=['integration', 'entity', 'status'], name='shopify_int_integra_c8c446_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifysynclog',
            index=models.Index(fields=['tenant_id', 'started_at'], name='shopify_int_tenant__8bc2d1_idx'),
        ),
    ]
