# Generated by Django 5.1.1 on 2025-01-27

from django.db import migrations, models


def get_default_api_version():
    """Get default API version from environment or use default."""
    import os
    return os.getenv("SHOPIFY_API_VERSION", "2024-10")


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_integration', '0003_add_error_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyintegration',
            name='api_version',
            field=models.CharField(
                default=get_default_api_version,
                help_text='Shopify API version used for requests',
                max_length=20
            ),
        ),
    ]

