# Generated by Django 5.1.1 on 2025-11-27 21:37

import shopify_integration.models.shopify_integration
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_integration', '0004_alter_shopifyintegration_api_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyintegration',
            name='api_version',
            field=models.CharField(default=shopify_integration.models.shopify_integration._get_default_api_version, help_text='Shopify API version used for requests', max_length=20),
        ),
        migrations.AlterField(
            model_name='shopifyintegration',
            name='store_url',
            field=models.CharField(help_text='Primary Shopify store URL (e.g. mystore.myshopify.com or https://mystore.myshopify.com)', max_length=255),
        ),
    ]
