# Generated by Django 5.1.1 on 2025-11-27 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_integration', '0007_create_sync_queue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='syncqueueitem',
            new_name='shopify_int_integra_1c681d_idx',
            old_name='shopify_queue_status_idx',
        ),
        migrations.RenameIndex(
            model_name='syncqueueitem',
            new_name='shopify_int_status_64da51_idx',
            old_name='shopify_queue_scheduled_idx',
        ),
        migrations.RenameIndex(
            model_name='syncqueueitem',
            new_name='shopify_int_tenant__e63ad2_idx',
            old_name='shopify_queue_tenant_idx',
        ),
        migrations.AddField(
            model_name='syncqueueitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopify_integration_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syncqueueitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopify_integration_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
