# Generated by Django 5.1.1 on 2025-11-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant ID for multi-tenant isolation')),
                ('customer_code', models.CharField(blank=True, db_index=True, max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('shopify_id', models.CharField(blank=True, help_text='Shopify customer ID', max_length=50)),
                ('shopify_created_at', models.DateTimeField(blank=True, help_text='Shopify creation date', null=True)),
                ('shopify_updated_at', models.DateTimeField(blank=True, help_text='Shopify last update date', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant ID for multi-tenant isolation')),
                ('order_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('channel', models.CharField(choices=[('manual', 'Manual'), ('shopify', 'Shopify')], default='manual', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=40)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('shopify_id', models.CharField(blank=True, help_text='Shopify order ID', max_length=50)),
                ('shopify_order_number', models.CharField(blank=True, help_text='Shopify order number', max_length=50)),
                ('shopify_customer_id', models.CharField(blank=True, help_text='Shopify customer ID', max_length=50)),
                ('shopify_created_at', models.DateTimeField(blank=True, help_text='Shopify creation date', null=True)),
                ('shopify_updated_at', models.DateTimeField(blank=True, help_text='Shopify last update date', null=True)),
                ('shopify_financial_status', models.CharField(blank=True, help_text='Shopify financial status', max_length=50)),
                ('shopify_fulfillment_status', models.CharField(blank=True, help_text='Shopify fulfillment status', max_length=50)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant ID for multi-tenant isolation')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
