# Generated by Django 5.1.1 on 2025-11-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant ID for multi-tenant isolation')),
                ('condition', models.CharField(max_length=200)),
                ('operator', models.CharField(default='LT', max_length=10)),
                ('value', models.CharField(default='0', max_length=120)),
                ('action', models.CharField(max_length=200)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
