# Generated by Django 5.1.1 on 2025-11-08 17:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant ID for multi-tenant isolation')),
                ('batch_number', models.CharField(db_index=True, max_length=100)),
                ('lot_number', models.CharField(blank=True, max_length=100)),
                ('manufacture_date', models.DateField()),
                ('expiry_date', models.DateField(db_index=True)),
                ('initial_quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('current_quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('quarantine', 'Quarantine'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('recalled', 'Recalled')], default='quarantine', max_length=20)),
                ('certificate_of_analysis', models.FileField(blank=True, null=True, upload_to='coa/')),
                ('qc_notes', models.TextField(blank=True)),
                ('storage_location', models.CharField(blank=True, help_text='e.g., Shelf A-12', max_length=100)),
                ('serial_numbers', models.JSONField(blank=True, default=list, help_text='List of serial numbers for track-and-trace compliance')),
                ('purchase_order_number', models.CharField(blank=True, max_length=100)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'Drug Batches',
                'ordering': ['expiry_date', 'batch_number'],
            },
        ),
        migrations.CreateModel(
            name='DrugDispensing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant ID for multi-tenant isolation')),
                ('dispensing_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('quantity_dispensed', models.DecimalField(decimal_places=3, help_text='Quantity at the specified packaging level', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('quantity_in_base_units', models.DecimalField(decimal_places=3, help_text='Automatically calculated quantity in base units', max_digits=12)),
                ('patient_name', models.CharField(blank=True, max_length=200)),
                ('prescription_number', models.CharField(blank=True, max_length=100)),
                ('prescriber_name', models.CharField(blank=True, max_length=200)),
                ('prescriber_license', models.CharField(blank=True, max_length=100)),
                ('dispensing_date', models.DateTimeField(auto_now_add=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dispensing_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-dispensing_date'],
            },
        ),
        migrations.CreateModel(
            name='DrugInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant ID for multi-tenant isolation')),
                ('quantity_available', models.DecimalField(decimal_places=3, default=0, help_text='Available for sale', max_digits=12)),
                ('quantity_reserved', models.DecimalField(decimal_places=3, default=0, help_text='Reserved for orders', max_digits=12)),
                ('quantity_quarantine', models.DecimalField(decimal_places=3, default=0, help_text='In quarantine/QC', max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('reorder_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Drug Inventories',
            },
        ),
        migrations.CreateModel(
            name='DrugProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant ID for multi-tenant isolation')),
                ('product_code', models.CharField(blank=True, db_index=True, help_text='Internal product code', max_length=100)),
                ('generic_name', models.CharField(help_text='Generic/INN name', max_length=200)),
                ('brand_name', models.CharField(blank=True, help_text='Brand/trade name', max_length=200)),
                ('dosage_form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('suspension', 'Suspension'), ('injection', 'Injection'), ('cream', 'Cream'), ('ointment', 'Ointment'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('powder', 'Powder'), ('solution', 'Solution'), ('other', 'Other')], max_length=50)),
                ('strength', models.CharField(help_text='e.g., 500mg, 10mg/ml', max_length=100)),
                ('route_of_administration', models.CharField(choices=[('oral', 'Oral'), ('topical', 'Topical'), ('intravenous', 'Intravenous (IV)'), ('intramuscular', 'Intramuscular (IM)'), ('subcutaneous', 'Subcutaneous (SC)'), ('inhalation', 'Inhalation'), ('rectal', 'Rectal'), ('ophthalmic', 'Ophthalmic'), ('otic', 'Otic'), ('nasal', 'Nasal'), ('transdermal', 'Transdermal')], max_length=50)),
                ('therapeutic_class', models.CharField(help_text='e.g., Antibiotic, Analgesic', max_length=200)),
                ('pharmacological_class', models.CharField(blank=True, help_text='e.g., Beta-lactam', max_length=200)),
                ('marketing_authorization_number', models.CharField(blank=True, help_text='Registration/MA number', max_length=100)),
                ('gtin', models.CharField(blank=True, help_text='Global Trade Item Number', max_length=14)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100)),
                ('ndc_code', models.CharField(blank=True, help_text='National Drug Code', max_length=50)),
                ('storage_conditions', models.CharField(choices=[('room_temp', 'Room Temperature (15-25°C)'), ('cool', 'Cool (8-15°C)'), ('refrigerated', 'Refrigerated (2-8°C)'), ('frozen', 'Frozen (-15°C or below)'), ('controlled_room', 'Controlled Room Temperature (20-25°C)')], max_length=50)),
                ('storage_instructions', models.TextField(blank=True, help_text='Additional storage requirements')),
                ('requires_cold_chain', models.BooleanField(default=False)),
                ('requires_prescription', models.BooleanField(default=True)),
                ('is_controlled_substance', models.BooleanField(default=False)),
                ('controlled_substance_schedule', models.CharField(blank=True, help_text='e.g., Schedule II', max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('importer', models.CharField(blank=True, max_length=200)),
                ('active_ingredients', models.TextField(help_text='Comma-separated list of active ingredients')),
                ('description', models.TextField(blank=True)),
                ('warnings', models.TextField(blank=True, help_text='Warnings and precautions')),
                ('status', models.CharField(choices=[('active', 'Active'), ('discontinued', 'Discontinued'), ('recalled', 'Recalled'), ('pending_approval', 'Pending Approval')], default='active', max_length=20)),
            ],
            options={
                'ordering': ['generic_name', 'strength'],
            },
        ),
        migrations.CreateModel(
            name='PackagingLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant ID for multi-tenant isolation')),
                ('level_name', models.CharField(help_text='e.g., Tablet, Strip, Box, Carton, Pallet', max_length=100)),
                ('level_order', models.IntegerField(help_text='Hierarchy order: 1=smallest (tablet/ml), 2=strip/bottle, 3=box, etc.')),
                ('base_unit_quantity', models.DecimalField(decimal_places=3, help_text='Quantity of base units in this packaging (e.g., 10 tablets per strip)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_of_measure', models.CharField(choices=[('unit', 'Unit (ea)'), ('tablet', 'Tablet'), ('capsule', 'Capsule'), ('ml', 'Milliliter'), ('gm', 'Gram'), ('strip', 'Strip'), ('bottle', 'Bottle'), ('vial', 'Vial'), ('ampoule', 'Ampoule'), ('box', 'Box'), ('carton', 'Carton'), ('pallet', 'Pallet')], max_length=50)),
                ('packaging_description', models.TextField(blank=True)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100)),
                ('gtin', models.CharField(blank=True, max_length=14)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('can_dispense', models.BooleanField(default=True, help_text='Can this packaging level be sold directly to customers?')),
                ('can_purchase', models.BooleanField(default=True, help_text='Can this packaging level be purchased from suppliers?')),
                ('length', models.DecimalField(blank=True, decimal_places=2, help_text='in cm', max_digits=8, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, help_text='in cm', max_digits=8, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='in cm', max_digits=8, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, help_text='in kg', max_digits=8, null=True)),
            ],
            options={
                'ordering': ['drug_product', 'level_order'],
            },
        ),
    ]
