# Generated by Django 5.1.1 on 2025-11-08 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharma', '0001_initial'),
        ('procurement', '0001_initial'),
        ('sales', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drugbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drugbatch',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.supplier'),
        ),
        migrations.AddField(
            model_name='drugbatch',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drugbatch',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drug_batches', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='drugdispensing',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensings', to='pharma.drugbatch'),
        ),
        migrations.AddField(
            model_name='drugdispensing',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drugdispensing',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customer'),
        ),
        migrations.AddField(
            model_name='drugdispensing',
            name='dispensed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_drugs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drugdispensing',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drug_dispensings', to='sales.order'),
        ),
        migrations.AddField(
            model_name='drugdispensing',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='druginventory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='druginventory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='druginventory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_inventory', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='drugproduct',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drugproduct',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drug_products', to='procurement.supplier'),
        ),
        migrations.AddField(
            model_name='drugproduct',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='druginventory',
            name='drug_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_status', to='pharma.drugproduct'),
        ),
        migrations.AddField(
            model_name='drugdispensing',
            name='drug_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensings', to='pharma.drugproduct'),
        ),
        migrations.AddField(
            model_name='drugbatch',
            name='drug_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pharma.drugproduct'),
        ),
        migrations.AddField(
            model_name='packaginglevel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packaginglevel',
            name='drug_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_levels', to='pharma.drugproduct'),
        ),
        migrations.AddField(
            model_name='packaginglevel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='druginventory',
            name='packaging_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_status', to='pharma.packaginglevel'),
        ),
        migrations.AddField(
            model_name='drugdispensing',
            name='packaging_level',
            field=models.ForeignKey(help_text='Packaging level at which drug is dispensed', on_delete=django.db.models.deletion.PROTECT, to='pharma.packaginglevel'),
        ),
        migrations.AddField(
            model_name='drugbatch',
            name='packaging_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='pharma.packaginglevel'),
        ),
        migrations.AddIndex(
            model_name='drugproduct',
            index=models.Index(fields=['tenant_id', 'generic_name'], name='pharma_drug_tenant__6d4ae1_idx'),
        ),
        migrations.AddIndex(
            model_name='drugproduct',
            index=models.Index(fields=['tenant_id', 'brand_name'], name='pharma_drug_tenant__679b2a_idx'),
        ),
        migrations.AddIndex(
            model_name='drugproduct',
            index=models.Index(fields=['tenant_id', 'barcode'], name='pharma_drug_tenant__b36e0c_idx'),
        ),
        migrations.AddIndex(
            model_name='drugproduct',
            index=models.Index(fields=['tenant_id', 'status'], name='pharma_drug_tenant__ca3c28_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='drugproduct',
            unique_together={('tenant_id', 'product_code')},
        ),
        migrations.AddIndex(
            model_name='packaginglevel',
            index=models.Index(fields=['tenant_id', 'drug_product', 'level_order'], name='pharma_pack_tenant__d3a63f_idx'),
        ),
        migrations.AddIndex(
            model_name='packaginglevel',
            index=models.Index(fields=['barcode'], name='pharma_pack_barcode_06cbd4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='packaginglevel',
            unique_together={('drug_product', 'level_order')},
        ),
        migrations.AddIndex(
            model_name='druginventory',
            index=models.Index(fields=['tenant_id', 'drug_product', 'warehouse'], name='pharma_drug_tenant__78bb5c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='druginventory',
            unique_together={('tenant_id', 'drug_product', 'warehouse', 'packaging_level')},
        ),
        migrations.AddIndex(
            model_name='drugdispensing',
            index=models.Index(fields=['tenant_id', '-dispensing_date'], name='pharma_drug_tenant__77ac66_idx'),
        ),
        migrations.AddIndex(
            model_name='drugdispensing',
            index=models.Index(fields=['drug_product', '-dispensing_date'], name='pharma_drug_drug_pr_87f865_idx'),
        ),
        migrations.AddIndex(
            model_name='drugdispensing',
            index=models.Index(fields=['batch'], name='pharma_drug_batch_i_5cc37d_idx'),
        ),
        migrations.AddIndex(
            model_name='drugbatch',
            index=models.Index(fields=['tenant_id', 'expiry_date'], name='pharma_drug_tenant__a5ee92_idx'),
        ),
        migrations.AddIndex(
            model_name='drugbatch',
            index=models.Index(fields=['tenant_id', 'status'], name='pharma_drug_tenant__471de2_idx'),
        ),
        migrations.AddIndex(
            model_name='drugbatch',
            index=models.Index(fields=['drug_product', 'batch_number'], name='pharma_drug_drug_pr_1d6294_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='drugbatch',
            unique_together={('tenant_id', 'drug_product', 'batch_number')},
        ),
    ]
