# Generated by Django 5.1.1 on 2025-11-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant ID for multi-tenant isolation')),
                ('product_code', models.CharField(blank=True, db_index=True, max_length=100)),
                ('sku', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('unit', models.CharField(default='pcs', help_text='Unit of measurement: pcs, kg, liters, etc.', max_length=20)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity', models.IntegerField(default=0, help_text='Current stock quantity')),
                ('reorder_level', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=40)),
                ('shopify_id', models.CharField(blank=True, help_text='Shopify product ID', max_length=50)),
                ('shopify_variant_id', models.CharField(blank=True, help_text='Shopify variant ID', max_length=50)),
                ('shopify_inventory_item_id', models.CharField(blank=True, help_text='Shopify inventory item ID', max_length=50)),
                ('shopify_handle', models.CharField(blank=True, help_text='Shopify product handle', max_length=255)),
                ('shopify_tags', models.TextField(blank=True, help_text='Shopify product tags (comma-separated)')),
                ('shopify_created_at', models.DateTimeField(blank=True, help_text='Shopify creation date', null=True)),
                ('shopify_updated_at', models.DateTimeField(blank=True, help_text='Shopify last update date', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant ID for multi-tenant isolation')),
                ('quantity', models.IntegerField()),
                ('movement_type', models.CharField(choices=[('in', 'In'), ('out', 'Out'), ('transfer', 'Transfer')], max_length=10)),
                ('reason', models.TextField(blank=True, help_text='Reason for stock adjustment')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
