# Generated by Django 5.1.1 on 2025-11-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_add_source_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='committed',
            field=models.IntegerField(default=0, help_text='Quantity committed/reserved (e.g., in orders)'),
        ),
        migrations.AddField(
            model_name='product',
            name='incoming',
            field=models.IntegerField(default=0, help_text='Quantity incoming (e.g., in transit)'),
        ),
        migrations.AddField(
            model_name='product',
            name='shopify_location_id',
            field=models.CharField(blank=True, help_text='Shopify location ID where inventory is stored', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Current stock quantity (available)'),
        ),
    ]
