# Generated by Django 5.1.1 on 2025-11-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant ID for multi-tenant isolation')),
                ('store_url', models.CharField(help_text='Shopify store URL (e.g., mystore.myshopify.com)', max_length=255)),
                ('api_key', models.CharField(help_text='Shopify API key', max_length=255)),
                ('api_secret', models.CharField(help_text='Shopify API secret', max_length=255)),
                ('access_token', models.CharField(blank=True, help_text='Shopify access token', max_length=255)),
                ('status', models.CharField(choices=[('DISCONNECTED', 'Disconnected'), ('CONNECTED', 'Connected'), ('SYNCING', 'Syncing'), ('ERROR', 'Error'), ('PAUSED', 'Paused')], default='DISCONNECTED', max_length=40)),
                ('last_sync', models.DateTimeField(blank=True, help_text='Last successful sync', null=True)),
                ('last_sync_products', models.DateTimeField(blank=True, null=True)),
                ('last_sync_orders', models.DateTimeField(blank=True, null=True)),
                ('last_sync_customers', models.DateTimeField(blank=True, null=True)),
                ('last_sync_inventory', models.DateTimeField(blank=True, null=True)),
                ('auto_sync_enabled', models.BooleanField(default=True, help_text='Enable automatic syncing')),
                ('sync_products', models.BooleanField(default=True, help_text='Sync products')),
                ('sync_orders', models.BooleanField(default=True, help_text='Sync orders')),
                ('sync_customers', models.BooleanField(default=True, help_text='Sync customers')),
                ('sync_inventory', models.BooleanField(default=True, help_text='Sync inventory levels')),
                ('webhook_secret', models.CharField(blank=True, help_text='Webhook secret for verification', max_length=255)),
                ('webhooks_enabled', models.BooleanField(default=True, help_text='Enable webhooks for real-time updates')),
                ('last_error', models.TextField(blank=True, help_text='Last error message')),
                ('error_count', models.IntegerField(default=0, help_text='Number of consecutive errors')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shopify Integration',
                'verbose_name_plural': 'Shopify Integrations',
            },
        ),
        migrations.CreateModel(
            name='ShopifySyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant ID for multi-tenant isolation')),
                ('sync_type', models.CharField(choices=[('FULL', 'Full Sync'), ('PRODUCTS', 'Products'), ('ORDERS', 'Orders'), ('CUSTOMERS', 'Customers'), ('INVENTORY', 'Inventory')], max_length=20)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('SUCCESS', 'Success'), ('ERROR', 'Error'), ('PARTIAL', 'Partial Success')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('items_processed', models.IntegerField(default=0)),
                ('items_created', models.IntegerField(default=0)),
                ('items_updated', models.IntegerField(default=0)),
                ('items_failed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Shopify Sync Log',
                'verbose_name_plural': 'Shopify Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
