# Generated by Django 5.1.1 on 2025-11-18 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailServiceIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant ID for multi-tenant isolation')),
                ('service_provider', models.CharField(choices=[('SMTP', 'SMTP'), ('SENDGRID', 'SendGrid'), ('MAILGUN', 'Mailgun'), ('AWS_SES', 'AWS SES'), ('GMAIL', 'Gmail')], default='SMTP', help_text='Email service provider', max_length=50)),
                ('smtp_host', models.CharField(help_text='SMTP server host', max_length=255)),
                ('smtp_port', models.IntegerField(default=587, help_text='SMTP server port')),
                ('smtp_username', models.CharField(help_text='SMTP username/email', max_length=255)),
                ('smtp_password', models.CharField(help_text='SMTP password', max_length=255)),
                ('use_tls', models.BooleanField(default=True, help_text='Use TLS encryption')),
                ('use_ssl', models.BooleanField(default=False, help_text='Use SSL encryption')),
                ('api_key', models.CharField(blank=True, help_text='Service API key', max_length=255)),
                ('api_secret', models.CharField(blank=True, help_text='Service API secret', max_length=255)),
                ('from_email', models.EmailField(help_text='Default from email address', max_length=254)),
                ('from_name', models.CharField(blank=True, help_text='Default from name', max_length=255)),
                ('status', models.CharField(choices=[('DISCONNECTED', 'Disconnected'), ('CONNECTED', 'Connected'), ('ERROR', 'Error'), ('PAUSED', 'Paused')], default='DISCONNECTED', max_length=40)),
                ('enable_sending', models.BooleanField(default=True, help_text='Enable email sending')),
                ('daily_limit', models.IntegerField(default=1000, help_text='Daily email sending limit')),
                ('emails_sent_today', models.IntegerField(default=0, help_text='Emails sent today')),
                ('last_reset_date', models.DateField(blank=True, help_text='Last date emails_sent_today was reset', null=True)),
                ('last_error', models.TextField(blank=True, help_text='Last error message')),
                ('error_count', models.IntegerField(default=0, help_text='Number of consecutive errors')),
                ('last_test_at', models.DateTimeField(blank=True, help_text='Last connection test', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Service Integration',
                'verbose_name_plural': 'Email Service Integrations',
                'unique_together': {('tenant_id',)},
            },
        ),
        migrations.CreateModel(
            name='StripeIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant ID for multi-tenant isolation')),
                ('publishable_key', models.CharField(help_text='Stripe publishable key', max_length=255)),
                ('secret_key', models.CharField(help_text='Stripe secret key', max_length=255)),
                ('webhook_secret', models.CharField(blank=True, help_text='Stripe webhook secret', max_length=255)),
                ('status', models.CharField(choices=[('DISCONNECTED', 'Disconnected'), ('CONNECTED', 'Connected'), ('ERROR', 'Error'), ('PAUSED', 'Paused')], default='DISCONNECTED', max_length=40)),
                ('test_mode', models.BooleanField(default=True, help_text='Use Stripe test mode')),
                ('auto_capture', models.BooleanField(default=True, help_text='Automatically capture payments')),
                ('enable_webhooks', models.BooleanField(default=True, help_text='Enable webhook processing')),
                ('last_error', models.TextField(blank=True, help_text='Last error message')),
                ('error_count', models.IntegerField(default=0, help_text='Number of consecutive errors')),
                ('last_test_at', models.DateTimeField(blank=True, help_text='Last connection test', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stripe Integration',
                'verbose_name_plural': 'Stripe Integrations',
                'unique_together': {('tenant_id',)},
            },
        ),
    ]
